### ISSUE TITLE
Screen issue on demo site using Firefox browser

### ISSUE THREAD

**Issue by faraz-b** [T-vK/SuperParticles#4]
Just a heads up, the demo website (https://t-vk.github.io/SuperParticles/demo.html) does not work properly with Mozilla Firefox. Upon arrival, I was met with a quick flash of the green gradient background and then turns to all black with the config button in the top right. See screenshot below:

![image](https://user-images.githubusercontent.com/38684511/78790133-f3aa4680-7962-11ea-9456-066850acda34.png)

Using Firefox Version 74.0.1 (64-bit)

**Comment by T-vK** [comment]
It work fine for me in Firefox 74 64-bit on Linux. Do you get any errors in the console? Are any addons or setting interfering? 
What is your operating system btw? And can you give me information on what graphics card you are using and if you have hardware acceleration enabled in Firefox?

**Comment by faraz-b** [comment]
No errors, in console, just `PixiJS 5.0.0-rc - WebGL 2 - http://www.pixijs.com/`

Disabled all addons but same result.

OS: Windows 10 Version 1809 Build 17763.1098
GPU: AMD Radeon R9 280X
Firefox hardware acceleration: Yes

**Comment by faraz-b** [comment]
So... I just updated Firefox to version 75.0 and now it works! 

Don't know what happened there, but thank you for making this, I will be using it for my personal website as Particles.js is waaaay too slow.
